### PR TITLE
Fix/356 ttscreenshotteractive causes npe at collected assertions

### LINKED ISSUE #356: `tt.screenshotter.active` causes NPE at collected assertions
**Describe the bug**
* Set `tt.screenshotter.active=false`
* Collect assertions with `CONTROL.collectAssertions()`
* NPE in `at eu.tsystems.mms.tic.testframework.execution.testng.DefaultCollectedAssertion.lambda$fail$1(DefaultCollectedAssertion.java:45)`

**Cause**
`TestEvidenceCollector.collectScreenshots()` can return null instead of a list. This is not handled in `DefaultCollectedAssertion`.

**Solution**
Return an empty list instead of `NULL`

**Workaround**
Don't set `tt.screenshotter.active=false` ;-)

### PR DESCRIPTION
**Pull request by martingrossmann**
# Description

Fixes an NPE when using property `tt.screenshotter.active=false`.

Fixes #356 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/DefaultOptionalAssertion.java [hunk 1]
```diff
@@ -46,11 +46,13 @@ public void fail(Error error) {
 
             // get screenshots
             List<Screenshot> screenshots = TestEvidenceCollector.collectScreenshots();
-            Report report = Testerra.getInjector().getInstance(Report.class);
-            screenshots.forEach(screenshot -> {
-                methodContext.addScreenshot(screenshot);
-                report.addScreenshot(screenshot, Report.FileMode.MOVE);
-            });
+            if (screenshots != null) {
```
Comment (mreiche) [inline core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/DefaultOptionalAssertion.java:49]: Isn't this double gemoppeld?

Comment (martingrossmann) [reply core/src/main/java/eu/tsystems/mms/tic/testframework/execution/testng/DefaultOptionalAssertion.java]: Indeed...

**Review by mreiche — APPROVED** [review]
