### PR TITLE
Fixed parsing filename from Content Disposition header.

### LINKED ISSUE #73: FileDownloader doesn't test Content disposition header
**Describe the bug**
The `FileDownloaderTest.test04_readFileNameFromResponseHeader` is not really testing that the file name is read from the HTTP  header.

### PR DESCRIPTION
**Pull request by mreiche**
Fixes #73

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/FileDownloaderTest.java [hunk 1]
```diff
@@ -106,6 +109,16 @@ public void test03_downloadFileToLongLocation() throws IOException {
         Assert.assertTrue(file.exists(), "File was downloaded correctly.");
     }
 
+    @Test
+    public void test_ContentDisposition_parsing() {
```
Comment (erickubenka) [inline integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/FileDownloaderTest.java:113]: This testcase does not test a behaviour of Testerra, right? It's just using the same logic/implementation that Testerra will use under the hood.

So what's the matter of executing it, when not testing the actual behaviour of Testerra?

**Review by erickubenka — CHANGES_REQUESTED** [review]

File: integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/FileDownloaderTest.java (hunk 1 above)
Comment (mreiche) [reply integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/FileDownloaderTest.java:113]: Because the already implemented test is wrong. It actually doesn't test reading the file name from content disposition header, because the file from Wikipedia doesn't provide it. And I did not found a public available picture with content-disposition header to fix the test.

**Review by martingrossmann — APPROVED** [review]

File: integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/FileDownloaderTest.java (hunk 1 above)
Comment (erickubenka) [reply integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/FileDownloaderTest.java:113]: Okay, that's the same thoughts I had on that.
Is it possible to provide such a file downlaod in test-sites that are used for integration-testing?

Comment (mreiche) [reply integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/FileDownloaderTest.java:113]: Only when I'm able to provide the header information, so this is just much more effort than just use a public file that provides it.

**Review by erickubenka — DISMISSED** [review]

**Review by mbeuthan — DISMISSED** [review]

File: integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/FileDownloaderTest.java [hunk 2]
```diff
@@ -49,19 +51,26 @@ public void tearDown(Method method) {
         new FileDownloader().cleanup();
     }
 
+    public DefaultConnectionConfigurator createConnectionConfigurator() {
```
Comment (mreiche) [inline integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/FileDownloaderTest.java:54]: I improved the `FileDownloader` API to set an `ConnectionConfigurator` which is basically just a `Consumer<URLConnection>` which gives more control for each download. The reason is described below.

File: integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/FileDownloaderTest.java [hunk 3]
```diff
@@ -97,29 +101,28 @@ public void testT02_downloadFileOfHttpsUrl() throws IOException {
...
     @Test
     public void test04_readFileNameFromResponseHeader() throws IOException {
-        WebDriver driver = WebDriverManager.getWebDriver();
         FileDownloader downloader = new FileDownloader();
-        File file = downloader.download(driver, "https://upload.wikimedia.org/wikipedia/de/thumb/e/e1/Java-Logo.svg/800px-Java-Logo.svg.png");
-        Assert.assertEquals(file.getName(), "800px-Java-Logo.svg");
+        DefaultConnectionConfigurator connectionConfigurator = createConnectionConfigurator();
+        connectionConfigurator.setHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9");
+        downloader.setConnectionConfigurator(connectionConfigurator);
+        File file = downloader.download( "https://images.pexels.com/users/avatars/616468/kira-schwarz-869.jpeg?auto=compress&fit=crop&h=256&w=256");
```
Comment (mreiche) [inline integration-tests/src/test/java/eu/tsystems/mms/tic/testframework/test/utils/FileDownloaderTest.java:118]: The reason is here, the `Content-Disposition` header is only send by `images.pexels.com` when the `Accept` header for `image/webp` is available AND, much more important: the `User-Agent` is defined. Otherwise, the host will send an `503 Service Unavailable`.

File: driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/DefaultConnectionConfigurator.java [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+import java.net.URLConnection;
+import java.time.Duration;
+import java.util.HashMap;
+import java.util.Map;
+import java.util.concurrent.TimeUnit;
+import java.util.function.Consumer;
+import javax.net.ssl.HttpsURLConnection;
+import org.openqa.selenium.WebDriver;
+
+public class DefaultConnectionConfigurator implements Consumer<URLConnection> {
```
Comment (mreiche) [inline driver-ui/src/main/java/eu/tsystems/mms/tic/testframework/utils/DefaultConnectionConfigurator.java:33]: The `DefaultConnectionConfiguration` implements all the features of `FileDownloader` but abstract and reusable using `CertUtils` and `URLConnection`.

**Comment by martingrossmann** [comment]
@mreiche Looks great. Please update the section https://docs.testerra.io/testerra/stable/index.html#_download_utilities in our documentation with usage of the `DefaultConnectionConfigurator`.

**Comment by mreiche** [comment]
> @mreiche Looks great. Please update the section https://docs.testerra.io/testerra/stable/index.html#_download_utilities in our documentation with usage of the `DefaultConnectionConfigurator`.

Yes, documentation update follows.

**Review by martingrossmann — APPROVED** [review]

**Review by mbeuthan — APPROVED** [review]
